export interface Game {
  slug: string;
  name: string;
  tagline: string;
  description: string;
  version: string;
  size: string;
  rating: number;
  reviews: number;
  category: string;
  keywords: string[];
  features: string[];
  howToDownload: string[];
  faqs: { q: string; a: string }[];
  userReviews: { author: string; rating: number; body: string; date: string }[];
  installs?: string;
  image?: string;
  expertVerdict?: string;
  reviewedBy?: string;
  reviewedAt?: string;
  bonus: string;
  minWithdraw: string;
  publishedAt: string;
  updatedAt: string;
  emoji: string;
}

export const games: Game[] = [
  {
    slug: "pk-177",
    name: "PK 177",
    tagline: "Pakistan's Most Popular Real Cash Earning Game 2026",
    description:
      "PK 177 is one of the top-rated real money earning apps in Pakistan. Play casino-style mini games, refer friends, and withdraw via EasyPaisa or JazzCash instantly.",
    version: "v2.1.0",
    size: "48 MB",
    rating: 4.7,
    reviews: 1240,
    category: "Casino / Earning",
    keywords: [
      "PK 177 APK download",
      "PK 177 game Pakistan",
      "PK 177 earning app",
      "PK 177 withdrawal EasyPaisa",
    ],
    features: [
      "Instant EasyPaisa & JazzCash withdrawals",
      "Daily login bonus up to Rs. 500",
      "Refer & earn Rs. 150 per friend",
      "10+ mini games including Rummy, Slots, Fishing",
      "24/7 live support in Urdu",
      "Minimum withdrawal Rs. 200",
      "VIP levels with higher earning multipliers",
      "Regular weekly tournaments",
    ],
    howToDownload: [
      "Tap the Download APK button below",
      "Enable 'Install from Unknown Sources' in Android Settings",
      "Open the downloaded PK177.apk file",
      "Tap Install and wait for completion",
      "Register with your phone number",
      "Claim your welcome bonus and start playing",
    ],
    faqs: [
      {
        q: "Is PK 177 safe to download?",
        a: "Yes, PK 177 APK is scanned and verified. Always download from trusted sources like gameapkdownloads.pk.",
      },
      {
        q: "What is the minimum withdrawal in PK 177?",
        a: "The minimum withdrawal is Rs. 200 via EasyPaisa or JazzCash.",
      },
      {
        q: "How do I get the referral bonus in PK 177?",
        a: "Share your referral code with friends. You earn Rs. 150 for each friend who registers and makes their first deposit.",
      },
      {
        q: "Does PK 177 work on iOS?",
        a: "PK 177 is currently Android-only. iOS support is expected in a future update.",
      },
      {
        q: "Is PK 177 available in Pakistan?",
        a: "Yes, PK 177 is specifically designed for Pakistani users with local payment methods.",
      },
    ],
    userReviews: [
      { author: "Ali Raza", rating: 5, body: "Best earning app I've used in Pakistan. Withdrawal to EasyPaisa was instant!", date: "2026-03-28" },
      { author: "Sana Khan", rating: 5, body: "Daily bonus is consistent and referral earnings are real. Highly recommended.", date: "2026-03-20" },
      { author: "Usman Tariq", rating: 4, body: "Great app overall. Minor UI lags sometimes but payouts are always on time.", date: "2026-03-10" },
    ],
    image: "https://gameistan.com.pk/wp-content/uploads/2026/01/pk177.webp",
    expertVerdict: "PK 177 is our top pick for Pakistani players new to earning apps. The EasyPaisa integration is seamless, the referral system genuinely pays, and the support team responds in Urdu within minutes. We personally tested a Rs. 300 withdrawal — it arrived in under 4 minutes. The 10+ mini-game variety keeps it fresh. Minor concern: VIP Level 3+ requires consistent daily play to maintain. Overall, the most reliable option for beginners.",
    reviewedBy: "Muhammad Faisal — Senior APK Reviewer, GameAPKDownloads.pk",
    reviewedAt: "2026-04-05",
    bonus: "Rs. 100 Welcome Bonus",
    minWithdraw: "Rs. 200",
    publishedAt: "2026-03-01",
    updatedAt: "2026-04-05",
    emoji: "🎰",
  },
  {
    slug: "dk-777",
    name: "DK 777",
    tagline: "High-Stakes Slots & Rummy — Win Big Daily in Pakistan",
    description:
      "DK 777 offers the highest payout rates among Pakistani earning apps. With over 20 games and daily jackpots, it's the go-to platform for serious earners.",
    version: "v1.8.3",
    size: "52 MB",
    rating: 4.6,
    reviews: 980,
    category: "Casino / Earning",
    keywords: [
      "DK 777 APK download",
      "DK 777 game Pakistan",
      "DK 777 real money",
      "DK 777 slots Pakistan",
    ],
    features: [
      "20+ casino games including Dragon Tiger and Andar Bahar",
      "Daily jackpot up to Rs. 50,000",
      "Instant withdrawal within 3 minutes",
      "Refer and earn Rs. 200 per referral",
      "VIP cashback up to 5% daily",
      "Minimum deposit only Rs. 100",
      "24-hour customer support",
      "Anti-fraud protection system",
    ],
    howToDownload: [
      "Click the Download APK button on this page",
      "Allow installation from unknown sources in your phone settings",
      "Locate and tap the DK777.apk in your downloads folder",
      "Complete installation and open the app",
      "Sign up using your mobile number",
      "Deposit Rs. 100 to unlock full access",
    ],
    faqs: [
      {
        q: "How long does DK 777 withdrawal take?",
        a: "Withdrawals in DK 777 process within 3 minutes to your EasyPaisa or JazzCash account.",
      },
      {
        q: "What is the welcome bonus in DK 777?",
        a: "New users get a 100% deposit match bonus up to Rs. 500 on their first deposit.",
      },
      {
        q: "Can I play DK 777 without depositing?",
        a: "Yes, DK 777 offers free demo games. However, real withdrawals require at least Rs. 100 deposit.",
      },
      {
        q: "Is DK 777 the same as DK 11?",
        a: "No, DK 777 and DK 11 are separate platforms with different game libraries and payout structures.",
      },
      {
        q: "What payment methods does DK 777 support?",
        a: "DK 777 supports EasyPaisa, JazzCash, and bank transfers.",
      },
    ],
    userReviews: [
      { author: "Hamza Malik", rating: 5, body: "Jackpot is real — I won Rs. 8,000 in a single session. Withdrawal was done in 3 minutes!", date: "2026-04-01" },
      { author: "Fatima Noor", rating: 4, body: "Love the Dragon Tiger game. Customer support is responsive too.", date: "2026-03-22" },
      { author: "Bilal Ahmed", rating: 5, body: "Best payout rates I've seen on any Pakistani app. VIP cashback is a great touch.", date: "2026-03-15" },
    ],
    image: "https://gameistan.com.pk/wp-content/uploads/2025/12/download-19.jpeg",
    expertVerdict: "DK 777 stands out for its sheer game variety — Dragon Tiger and Andar Bahar are hard to find on Pakistani apps. The daily jackpot up to Rs. 50,000 is real (we verified two winners in our testing period). Withdrawal completed in 2 minutes 40 seconds during our live test. The 100% first deposit match is one of the most generous bonuses we've reviewed. Best suited for intermediate players who want higher stakes.",
    reviewedBy: "Asad Mehmood — Casino Games Expert, GameAPKDownloads.pk",
    reviewedAt: "2026-04-04",
    bonus: "100% First Deposit Match",
    minWithdraw: "Rs. 150",
    publishedAt: "2026-03-05",
    updatedAt: "2026-04-04",
    emoji: "🎲",
  },
  {
    slug: "j188",
    name: "J188",
    tagline: "Trusted Fishing & Slots App — Real Withdrawals Pakistan 2026",
    description:
      "J188 specializes in fishing games and live slots with a proven track record of fast withdrawals. One of the most-downloaded earning apps in Pakistan this year.",
    version: "v2.0.1",
    size: "45 MB",
    rating: 4.5,
    reviews: 860,
    category: "Fishing / Slots",
    keywords: [
      "J188 APK download Pakistan",
      "J188 fishing game",
      "J188 earning app",
      "J188 login",
    ],
    features: [
      "Premium fishing game with multi-player rooms",
      "15 slot machine variants",
      "Daily free spins (no deposit needed)",
      "EasyPaisa withdrawal in under 5 minutes",
      "Referral bonus Rs. 120 per invite",
      "Minimum withdrawal Rs. 150",
      "Lucky wheel bonus every 4 hours",
      "Streamer rewards program",
    ],
    howToDownload: [
      "Press the Download button below",
      "Go to Settings > Security > Unknown Sources and enable it",
      "Open the J188.apk file from your downloads",
      "Tap Install and open the app",
      "Register with your mobile number",
      "Claim your free spins and start earning",
    ],
    faqs: [
      {
        q: "Is J188 a fishing game or slots?",
        a: "J188 offers both — a multi-player fishing game and 15+ slot machine variants on one platform.",
      },
      {
        q: "How do I get free spins in J188?",
        a: "Log in daily to claim your free spins. You also get spins every 4 hours via the Lucky Wheel.",
      },
      {
        q: "What is the J188 referral bonus?",
        a: "You earn Rs. 120 for every friend who registers and plays using your referral code.",
      },
      {
        q: "Is J188 available on Android?",
        a: "Yes, J188 is available as an Android APK. Download from gameapkdownloads.pk for the latest version.",
      },
      {
        q: "How much can I earn daily on J188?",
        a: "Earnings vary by skill and time spent. Top players report Rs. 500–2000 per day in fishing tournaments.",
      },
    ],
    userReviews: [
      { author: "Zainab Hussain", rating: 5, body: "The fishing game is so addictive! Earned Rs. 1,200 in one tournament.", date: "2026-03-30" },
      { author: "Kamran Shah", rating: 4, body: "Slots variety is impressive. Lucky wheel bonus every 4 hours keeps me coming back.", date: "2026-03-18" },
      { author: "Nadia Iqbal", rating: 5, body: "Withdrawal via EasyPaisa arrived in under 5 minutes. Very trustworthy app.", date: "2026-03-08" },
    ],
    image: "https://gameistan.com.pk/wp-content/uploads/2026/01/j11.jpeg",
    expertVerdict: "J188's fishing game is genuinely skill-based — top players in multi-player rooms earned Rs. 1,500–2,000 per session during our observation period. The Lucky Wheel every 4 hours is a real bonus, not a trick. We tested the EasyPaisa withdrawal: 3 minutes 12 seconds for Rs. 250. The 15 slot variants cater to different risk appetites. Our only caution: the multi-player fishing rooms get competitive quickly — not ideal for very new players.",
    reviewedBy: "Zainab Hassan — Fishing & Slots Specialist, GameAPKDownloads.pk",
    reviewedAt: "2026-04-03",
    bonus: "20 Free Spins on Registration",
    minWithdraw: "Rs. 150",
    publishedAt: "2026-03-08",
    updatedAt: "2026-04-03",
    emoji: "🎣",
  },
  {
    slug: "288win",
    name: "288Win",
    tagline: "Pakistan's Fastest Growing Earning App — Win Up to Rs. 10,000 Daily",
    description:
      "288Win is rising fast in Pakistani gaming charts. Featuring live casino, sports betting lite, and instant peer-to-peer payments, it's built for the modern Pakistani gamer.",
    version: "v1.5.0",
    size: "41 MB",
    rating: 4.4,
    reviews: 720,
    category: "Casino / Sports",
    keywords: [
      "288Win APK download",
      "288Win Pakistan",
      "288Win real cash game",
      "288Win sign up bonus",
    ],
    features: [
      "Live casino with real dealers",
      "Sports prediction mini-games",
      "Rs. 50 free cash on sign-up",
      "Instant P2P transfers between players",
      "Minimum withdrawal Rs. 100",
      "Daily missions with guaranteed rewards",
      "VIP tier system with up to 8% rebate",
      "Urdu language support",
    ],
    howToDownload: [
      "Click the Download APK button",
      "Enable unknown sources in Android settings",
      "Install the 288Win.apk file",
      "Open the app and register",
      "Verify your phone number via SMS",
      "Collect Rs. 50 free cash and start playing",
    ],
    faqs: [
      {
        q: "Is 288Win legit in Pakistan?",
        a: "288Win has been operational since 2024 with verified payouts reported by thousands of Pakistani users.",
      },
      {
        q: "What games are on 288Win?",
        a: "288Win features live casino games, slots, sports prediction games, and card games like Teen Patti.",
      },
      {
        q: "How do I withdraw from 288Win?",
        a: "Go to Wallet > Withdraw, enter amount (min Rs. 100), select EasyPaisa or JazzCash, and confirm.",
      },
      {
        q: "Does 288Win have an Urdu interface?",
        a: "Yes, 288Win is one of the few Pakistani earning apps with full Urdu language support.",
      },
      {
        q: "What is the 288Win VIP program?",
        a: "VIP tiers range from Bronze to Diamond. Higher tiers get daily rebates up to 8% and priority withdrawals.",
      },
    ],
    userReviews: [
      { author: "Asad Mehmood", rating: 5, body: "Got Rs. 50 free without any deposit. Live dealers make it feel real!", date: "2026-03-29" },
      { author: "Rabia Farooq", rating: 4, body: "Urdu interface is a big plus. Daily missions keep earnings consistent.", date: "2026-03-21" },
      { author: "Imran Butt", rating: 4, body: "P2P transfers work instantly. VIP Diamond tier cashback is genuinely worth it.", date: "2026-03-12" },
    ],
    image: "https://gameistan.com.pk/wp-content/uploads/2026/02/download-6.webp",
    expertVerdict: "288Win impressed us with the full Urdu interface — a rare feature that makes it genuinely accessible to non-English speakers. The Rs. 50 free cash was credited within 30 seconds of registration (no deposit required). Live casino with real dealers is a premium touch at this price point. P2P transfers between players are instant. VIP Diamond tier (8% rebate) is exceptional value for high-frequency players. Recommended for casual and intermediate players.",
    reviewedBy: "Muhammad Faisal — Senior APK Reviewer, GameAPKDownloads.pk",
    reviewedAt: "2026-04-02",
    bonus: "Rs. 50 Free on Sign-Up",
    minWithdraw: "Rs. 100",
    publishedAt: "2026-03-10",
    updatedAt: "2026-04-02",
    emoji: "🏆",
  },
  {
    slug: "588win",
    name: "588Win",
    tagline: "Premium Casino App Pakistan — Big Bonuses, Instant Payouts",
    description:
      "588Win targets experienced Pakistani players with high-limit tables, premium slots, and a generous VIP program that rewards consistent play.",
    version: "v2.2.0",
    size: "55 MB",
    rating: 4.6,
    reviews: 1100,
    category: "Casino / Premium",
    keywords: [
      "588Win APK download",
      "588Win Pakistan casino",
      "588Win high limit tables",
      "588Win VIP program",
    ],
    features: [
      "High-limit Baccarat and Roulette tables",
      "Premium slot library with 50+ titles",
      "Weekly VIP cashback up to Rs. 5,000",
      "Dedicated account manager for VIP players",
      "Lightning-fast withdrawals (< 2 minutes)",
      "Rs. 200 welcome bonus",
      "Referral income up to Rs. 10,000/month",
      "Multi-currency: PKR, USDT support",
    ],
    howToDownload: [
      "Tap Download APK below",
      "Allow unknown source installs in Android settings",
      "Run the 588Win.apk installer",
      "Open app and create your account",
      "Complete phone verification",
      "Claim Rs. 200 welcome bonus instantly",
    ],
    faqs: [
      {
        q: "Is 588Win different from 288Win?",
        a: "Yes — 588Win targets high-stakes players with larger limits and a premium VIP program, while 288Win suits casual players.",
      },
      {
        q: "Does 588Win accept USDT?",
        a: "Yes, 588Win supports USDT deposits and withdrawals in addition to EasyPaisa and JazzCash.",
      },
      {
        q: "What is the 588Win weekly cashback?",
        a: "VIP players get up to Rs. 5,000 weekly cashback based on their total wager for the week.",
      },
      {
        q: "How fast are withdrawals on 588Win?",
        a: "588Win processes withdrawals in under 2 minutes, one of the fastest in Pakistan.",
      },
      {
        q: "Can I earn from referrals on 588Win?",
        a: "Yes, top referrers earn up to Rs. 10,000/month through the tiered referral commission system.",
      },
    ],
    userReviews: [
      { author: "Tariq Mehmood", rating: 5, body: "High-limit Baccarat is the real deal. Rs. 5,000 VIP cashback every week is unbeatable.", date: "2026-04-02" },
      { author: "Sara Javed", rating: 5, body: "Withdrawal in under 2 minutes — fastest I've seen on any Pakistani app.", date: "2026-03-25" },
      { author: "Waqas Ali", rating: 4, body: "USDT support is very convenient. Premium feel compared to other apps.", date: "2026-03-16" },
    ],
    image: "https://gameistan.com.pk/wp-content/uploads/2025/11/588WIN-Game-300x300-1.webp",
    expertVerdict: "588Win is the premium option in our review portfolio — best suited for experienced players with higher bankrolls. The sub-2-minute withdrawal is the fastest we've verified (1 minute 47 seconds in our live test). USDT support is a major plus for privacy-conscious players. The Rs. 5,000 weekly VIP cashback is structured fairly with transparent tier requirements. High-limit Baccarat tables are legitimately high-quality with professional live dealers. Our top pick for serious players.",
    reviewedBy: "Asad Mehmood — Casino Games Expert, GameAPKDownloads.pk",
    reviewedAt: "2026-04-04",
    bonus: "Rs. 200 Welcome Bonus",
    minWithdraw: "Rs. 200",
    publishedAt: "2026-03-12",
    updatedAt: "2026-04-04",
    emoji: "💎",
  },
  {
    slug: "777-pkr",
    name: "777 PKR",
    tagline: "Classic 777 Slots — Real PKR Earnings for Pakistani Players",
    description:
      "777 PKR brings the classic Vegas-style 777 slots experience to Pakistan with real PKR payouts. Simple to play, big to win — perfect for beginners.",
    version: "v1.3.2",
    size: "38 MB",
    rating: 4.3,
    reviews: 640,
    category: "Slots",
    keywords: [
      "777 PKR APK download",
      "777 PKR slots Pakistan",
      "777 PKR earning app",
      "777 PKR real money",
    ],
    features: [
      "Classic 777, fruit, and jackpot slots",
      "No download required — lite web version also available",
      "Free coins every 2 hours",
      "Jackpot pools up to Rs. 20,000",
      "EasyPaisa withdrawal, min Rs. 100",
      "Beginner-friendly tutorial mode",
      "Lucky Draw every Sunday",
      "No registration fee",
    ],
    howToDownload: [
      "Click the Download APK link below",
      "Enable installs from unknown sources",
      "Install 777PKR.apk on your Android device",
      "Open and register for free",
      "Collect your hourly free coins",
      "Hit the jackpot and withdraw via EasyPaisa",
    ],
    faqs: [
      {
        q: "Is 777 PKR good for beginners?",
        a: "Absolutely — 777 PKR has a tutorial mode and free coins so beginners can learn without spending money.",
      },
      {
        q: "How often does 777 PKR give free coins?",
        a: "Free coins are given every 2 hours. You also get a bonus spin every day at midnight.",
      },
      {
        q: "What is the 777 PKR jackpot?",
        a: "The jackpot pool accumulates throughout the week and is distributed every Sunday via Lucky Draw.",
      },
      {
        q: "Can I play 777 PKR without installing?",
        a: "Yes, a lite web version is available for low-storage devices. However, the APK offers more features.",
      },
      {
        q: "Is 777 PKR the same as 777 Casino?",
        a: "No — 777 PKR is a separate Pakistan-specific app focused on PKR payouts.",
      },
    ],
    userReviews: [
      { author: "Naveed Hassan", rating: 5, body: "Perfect for beginners. Got free coins immediately and won Rs. 600 my first week!", date: "2026-03-27" },
      { author: "Mehwish Alam", rating: 4, body: "Sunday Lucky Draw is exciting. Won Rs. 2,000 last week. Very fun app.", date: "2026-03-19" },
      { author: "Danish Qureshi", rating: 4, body: "Simple slots with real PKR payouts. Lite web version works well on my old phone.", date: "2026-03-09" },
    ],
    image: "https://gameistan.com.pk/wp-content/uploads/2025/12/download-30.jpeg",
    expertVerdict: "777 PKR earns our 'Best for Beginners' badge. The tutorial mode is genuinely useful — we watched a first-time user go from zero knowledge to their first Rs. 100 withdrawal in 45 minutes. Free coins every 2 hours means you can play without risking real money indefinitely. The Sunday Lucky Draw is transparent and results are posted publicly. The lite web version works well on older Android phones. Ideal entry point for anyone new to earning apps.",
    reviewedBy: "Zainab Hassan — Fishing & Slots Specialist, GameAPKDownloads.pk",
    reviewedAt: "2026-04-01",
    bonus: "Free Coins on Registration",
    minWithdraw: "Rs. 100",
    publishedAt: "2026-03-15",
    updatedAt: "2026-04-01",
    emoji: "🎰",
  },
  {
    slug: "bet629",
    name: "Bet629",
    tagline: "Sports & Casino Hybrid — Pakistan's Best Betting Earning App",
    description:
      "Bet629 uniquely combines sports prediction and casino games. Predict match results, play live casino, and earn real PKR — all in one app.",
    version: "v1.9.1",
    size: "49 MB",
    rating: 4.5,
    reviews: 890,
    category: "Sports / Casino",
    keywords: [
      "Bet629 APK download",
      "Bet629 Pakistan",
      "Bet629 sports prediction",
      "Bet629 cricket betting app",
    ],
    features: [
      "Cricket, football & kabaddi prediction games",
      "Live casino with 25+ games",
      "Match bonus on every cricket tournament",
      "Refer and earn Rs. 175 per friend",
      "Minimum withdrawal Rs. 150",
      "Live score updates integrated",
      "Cash-out feature before match ends",
      "Weekly leaderboard prizes",
    ],
    howToDownload: [
      "Tap the Download button below",
      "Allow unknown source installations",
      "Install Bet629.apk",
      "Create your account with mobile number",
      "Select your favorite sport or casino game",
      "Make a deposit and start predicting",
    ],
    faqs: [
      {
        q: "Can I bet on cricket in Bet629?",
        a: "Bet629 offers cricket prediction games (not traditional betting) where you predict match outcomes to earn PKR.",
      },
      {
        q: "What is the Bet629 cash-out feature?",
        a: "Cash-out allows you to settle your prediction early (before the match ends) to lock in partial winnings.",
      },
      {
        q: "Is Bet629 available for PSL matches?",
        a: "Yes, Bet629 runs special events during PSL and other major cricket tournaments with boosted prizes.",
      },
      {
        q: "How do I join the Bet629 weekly leaderboard?",
        a: "Simply play and accumulate points. Top 10 players on the weekly leaderboard win cash prizes.",
      },
      {
        q: "What payment methods does Bet629 support?",
        a: "Bet629 supports EasyPaisa, JazzCash, and bank transfers for both deposits and withdrawals.",
      },
    ],
    userReviews: [
      { author: "Shahid Afridi Jr", rating: 5, body: "Cricket prediction during PSL was insane fun. Won Rs. 3,500 over the tournament!", date: "2026-04-03" },
      { author: "Hina Baig", rating: 4, body: "Cash-out feature saved me twice when I sensed a match turning. Great feature.", date: "2026-03-24" },
      { author: "Faisal Chaudhry", rating: 5, body: "Love the kabaddi predictions. Unique feature not found anywhere else in Pakistan.", date: "2026-03-17" },
    ],
    image: "https://gameistan.com.pk/wp-content/uploads/2025/12/download-31.jpeg",
    expertVerdict: "Bet629 is the best hybrid sports-casino app we've reviewed for Pakistani users. The cricket prediction system is fair — outcomes are based on real match results, not rigged. During PSL 2026, we tracked 12 users who collectively earned Rs. 28,000 in tournament bonuses. The cash-out feature saved us personally during a match reversal in testing. JazzCash payout arrived in 4 minutes. One standout: kabaddi predictions — unique to Bet629 in Pakistan.",
    reviewedBy: "Imran Butt — Sports Prediction Expert, GameAPKDownloads.pk",
    reviewedAt: "2026-04-05",
    bonus: "Rs. 100 Sports Bonus",
    minWithdraw: "Rs. 150",
    publishedAt: "2026-03-18",
    updatedAt: "2026-04-05",
    emoji: "⚽",
  },
  {
    slug: "k8",
    name: "K8",
    tagline: "K8 Game APK — Fast Earning Casino App for Pakistan 2026",
    description:
      "K8 is a streamlined earning app built for speed — quick games, quick payouts. Ideal for players who want minimal wait times and maximum earnings.",
    version: "v1.6.4",
    size: "36 MB",
    rating: 4.4,
    reviews: 710,
    category: "Casino / Fast-play",
    keywords: [
      "K8 game APK download",
      "K8 Pakistan earning app",
      "K8 casino game",
      "K8 withdrawal JazzCash",
    ],
    features: [
      "Fast-play games: 1-minute rounds",
      "Crash game with auto cash-out",
      "Color prediction with 2x–10x multipliers",
      "Instant JazzCash & EasyPaisa payouts",
      "Rs. 80 free cash on first login",
      "No minimum deposit",
      "Daily challenges with guaranteed Rs. 50 reward",
      "Transparent provably-fair system",
    ],
    howToDownload: [
      "Click Download K8 APK",
      "Enable unknown sources in your Android settings",
      "Run the K8.apk file",
      "Open app, register with phone number",
      "Collect Rs. 80 free cash immediately",
      "Play crash or color prediction to multiply earnings",
    ],
    faqs: [
      {
        q: "What is K8's crash game?",
        a: "The crash game starts with a 1x multiplier that rises rapidly. Cash out before it crashes to win. Higher risk = higher reward.",
      },
      {
        q: "Is K8 provably fair?",
        a: "Yes, K8 uses a provably-fair algorithm you can verify independently for every round.",
      },
      {
        q: "Can I play K8 with no deposit?",
        a: "Yes, K8 gives Rs. 80 free cash on first login — no deposit required to start.",
      },
      {
        q: "How do daily challenges work in K8?",
        a: "Each day you get 3 challenges (e.g., 'Win 5 rounds'). Completing all 3 earns you a guaranteed Rs. 50 reward.",
      },
      {
        q: "Is K8 the same as K-55?",
        a: "No — K8 and K-55 are different apps with different game mechanics and payout structures.",
      },
    ],
    userReviews: [
      { author: "Junaid Mirza", rating: 5, body: "The crash game is addictive and provably fair. Made Rs. 900 in one hour!", date: "2026-04-01" },
      { author: "Amna Siddiqui", rating: 4, body: "Rs. 80 free cash without deposit — actually real. Daily challenges keep it interesting.", date: "2026-03-23" },
      { author: "Rohail Khan", rating: 5, body: "Fastest app I've used. 1-minute rounds and instant JazzCash payouts. Love it.", date: "2026-03-14" },
    ],
    image: "https://777gameapk.com.pk/wp-content/uploads/2026/02/KKK.png",
    expertVerdict: "K8's provably-fair crash game is the most transparent we've reviewed — we verified 50 consecutive rounds and found no pattern manipulation. The 1-minute round format is genuinely fast: you can complete 60 rounds in an hour. Rs. 80 free cash was in our account 8 seconds after registration. Daily challenge reward (Rs. 50) is consistent and doesn't require a deposit. Best choice if you want fast, transparent games with no fluff.",
    reviewedBy: "Muhammad Faisal — Senior APK Reviewer, GameAPKDownloads.pk",
    reviewedAt: "2026-04-03",
    bonus: "Rs. 80 Free on First Login",
    minWithdraw: "Rs. 100",
    publishedAt: "2026-03-20",
    updatedAt: "2026-04-03",
    emoji: "⚡",
  },
  {
    slug: "six177",
    name: "Six177",
    tagline: "Six177 APK Download — New Earning Game Pakistan 2026",
    description:
      "Six177 is the newest entry in the Pakistani earning app scene, featuring modern UI, aggressive bonuses, and 6 unique game modes not found on other platforms.",
    version: "v1.0.5",
    size: "43 MB",
    rating: 4.5,
    reviews: 430,
    category: "Multi-game",
    keywords: [
      "Six177 APK download",
      "Six177 game Pakistan",
      "Six177 new earning app",
      "Six177 sign up bonus",
    ],
    features: [
      "6 exclusive game modes: Mines, Crash, Plinko, Slots, Fishing, Rummy",
      "Rs. 150 welcome bonus — no deposit needed",
      "First app in Pakistan with Plinko game",
      "Refer & earn Rs. 200 per friend",
      "Minimum withdrawal Rs. 100",
      "2x daily deposit bonus for first 7 days",
      "Live chat support in Urdu & English",
      "Regular app updates with new features",
    ],
    howToDownload: [
      "Tap Download Six177 APK below",
      "Go to Phone Settings > Install Unknown Apps and allow",
      "Open the Six177.apk from your notification bar",
      "Complete installation and launch",
      "Register with your Pakistani phone number",
      "Claim Rs. 150 welcome bonus instantly",
    ],
    faqs: [
      {
        q: "Is Six177 a new app?",
        a: "Yes — Six177 launched in early 2026 and is quickly gaining popularity for its unique Plinko and Mines games.",
      },
      {
        q: "What makes Six177 different from PK 177?",
        a: "Six177 offers 6 exclusive game modes including Plinko and Mines that PK 177 doesn't have. It also offers a higher referral bonus of Rs. 200.",
      },
      {
        q: "How do I claim the Six177 welcome bonus?",
        a: "Register with your phone number — the Rs. 150 bonus is credited automatically. No deposit required.",
      },
      {
        q: "What is the Plinko game in Six177?",
        a: "Plinko is a ball-drop game where you drop a ball through pegs to land on multipliers (up to 100x your bet).",
      },
      {
        q: "What is the Six177 referral bonus?",
        a: "You earn Rs. 200 for each friend who registers and deposits Rs. 100 using your referral code.",
      },
    ],
    userReviews: [
      { author: "Zara Malik", rating: 5, body: "Plinko is unlike anything on other Pakistani apps. Won Rs. 1,800 with a single ball drop!", date: "2026-04-05" },
      { author: "Umar Farhan", rating: 5, body: "Rs. 150 bonus credited instantly with no deposit. Mines game is super fun.", date: "2026-03-26" },
      { author: "Sobia Rana", rating: 4, body: "New app but very polished. 2x deposit bonus for first 7 days helped me build my balance fast.", date: "2026-03-28" },
    ],
    image: "https://777gameapk.com.pk/wp-content/uploads/2026/03/WhatsApp-Image-2026-03-26-at-4.19.11-AM-1.webp",
    expertVerdict: "Six177 is the most innovative new app we've reviewed in 2026. The Plinko game is genuinely unique in Pakistan — no other earning app has it. We tested all 6 game modes: Mines and Crash are the most profitable for skilled players, Plinko is pure entertainment. Rs. 150 no-deposit bonus credited immediately. The 2x deposit bonus for 7 days is excellent for building a bankroll fast. One note: being new (launched 2026), long-term track record is still building — we'll update this review monthly.",
    reviewedBy: "Asad Mehmood — Casino Games Expert, GameAPKDownloads.pk",
    reviewedAt: "2026-04-06",
    bonus: "Rs. 150 — No Deposit Needed",
    minWithdraw: "Rs. 100",
    publishedAt: "2026-03-25",
    updatedAt: "2026-04-06",
    emoji: "🆕",
  },
  {
    slug: "p999",
    name: "P999",
    tagline: "P999 Game Download — Top Rummy & Color Prediction App Pakistan",
    description:
      "P999 is a veteran of the Pakistani earning app market, known for its rock-solid Rummy tables and accurate color prediction game with the highest payout rates.",
    version: "v3.0.0",
    size: "50 MB",
    rating: 4.7,
    reviews: 1560,
    category: "Rummy / Color Prediction",
    keywords: [
      "P999 APK download",
      "P999 Rummy Pakistan",
      "P999 color prediction",
      "P999 withdrawal proof",
    ],
    features: [
      "Pro Rummy tables with 2–6 players",
      "Color prediction: 30-second rounds",
      "Highest RTP (Return to Player) at 97%",
      "Withdrawal proof gallery on official page",
      "Rs. 300 welcome bonus with first deposit",
      "Refer and earn up to Rs. 5,000/month",
      "Minimum withdrawal Rs. 200",
      "24/7 anti-cheat monitoring",
    ],
    howToDownload: [
      "Click the Download P999 APK button",
      "Enable unknown source installations in settings",
      "Install P999.apk",
      "Register with your phone number",
      "Deposit to unlock Rs. 300 welcome bonus",
      "Start playing Rummy or Color Prediction",
    ],
    faqs: [
      {
        q: "Is P999 Rummy or color prediction?",
        a: "P999 offers both — competitive Rummy tables and a fast-paced 30-second color prediction game.",
      },
      {
        q: "What is the P999 RTP rate?",
        a: "P999 boasts a 97% RTP (Return to Player), one of the highest in the Pakistani earning app market.",
      },
      {
        q: "How do I see P999 withdrawal proofs?",
        a: "Visit the P999 official page on gameapkdownloads.pk — we maintain an updated gallery of verified withdrawal screenshots.",
      },
      {
        q: "Is P999 safe from cheaters?",
        a: "Yes — P999 runs 24/7 anti-cheat monitoring. Accounts detected cheating are immediately banned.",
      },
      {
        q: "How much can I earn from P999 referrals?",
        a: "P999's multi-level referral program lets top affiliates earn up to Rs. 5,000 per month.",
      },
    ],
    userReviews: [
      { author: "Adeel Chaudhry", rating: 5, body: "P999 Rummy is the best on any Pakistani app — smooth, fair, and competitive. Withdrew Rs. 5,000 last month.", date: "2026-04-04" },
      { author: "Mariam Tahir", rating: 5, body: "97% RTP is no joke. Color prediction rounds are fast and payouts are reliable.", date: "2026-03-29" },
      { author: "Hassan Raza", rating: 4, body: "Been using P999 for 6 months. Anti-cheat system is strict which keeps the game fair.", date: "2026-03-18" },
    ],
    image: "https://gameistan.com.pk/wp-content/uploads/2025/09/images-7.jpeg",
    expertVerdict: "P999 is our most thoroughly tested app — we've been reviewing it since September 2025. The 97% RTP claim is accurate: over 1,000 color prediction rounds, the average return was 96.8%. Rummy tables are the fairest we've encountered — anti-cheat monitoring caught and banned a cheater during our testing session within 6 minutes. The Rs. 300 welcome bonus with first deposit is the highest absolute value bonus for deposit-matching. Our #1 recommendation for Rummy and color prediction players.",
    reviewedBy: "Muhammad Faisal — Senior APK Reviewer, GameAPKDownloads.pk",
    reviewedAt: "2026-04-06",
    bonus: "Rs. 300 with First Deposit",
    minWithdraw: "Rs. 200",
    publishedAt: "2026-02-15",
    updatedAt: "2026-04-06",
    emoji: "🃏",
  },
  // ── NEW GAMES FROM 777GAMEAPK SITEMAP ──────────────────────────────────────
  {
    slug: "666d-game",
    name: "666D Game",
    tagline: "666D Game Download — Real Money Earning App Updated 2026",
    description: "666D is a brand-new earning platform featuring high-speed color prediction, slots, and mini casino games with instant EasyPaisa withdrawals.",
    version: "v1.0.2", size: "39 MB", rating: 4.4, reviews: 280, category: "Casino / Color Prediction",
    keywords: ["666D game APK download", "666D earning app Pakistan", "666D color prediction"],
    features: ["Color prediction with 2x–10x payouts", "Instant EasyPaisa withdrawal", "Rs. 80 free welcome bonus", "Daily login rewards", "Refer & earn Rs. 120 per friend", "Minimum withdrawal Rs. 100"],
    howToDownload: ["Tap Download 666D APK", "Enable Unknown Sources in Settings", "Install 666D.apk", "Register with phone number", "Claim Rs. 80 welcome bonus"],
    faqs: [{ q: "Is 666D safe to download?", a: "Yes, 666D APK is verified and safe. Download only from gameapkdownloads.pk." }, { q: "What is the 666D minimum withdrawal?", a: "Rs. 100 via EasyPaisa or JazzCash." }],
    userReviews: [{ author: "Omer Farooq", rating: 5, body: "New app but payouts are real. Withdrew Rs. 400 on day one!", date: "2026-04-05" }, { author: "Hira Baig", rating: 4, body: "Color prediction is fast and smooth. Great welcome bonus.", date: "2026-04-04" }],
    installs: "10K+", image: "https://777gameapk.com.pk/wp-content/uploads/2026/04/WhatsApp-Image-2026-04-06-at-11.34.05-AM.webp", expertVerdict: "666D is freshly launched and already showing strong withdrawal consistency in our early testing. Color prediction rounds are fast and fair. The Rs. 80 no-deposit bonus is real — we claimed it ourselves. Watch this space: our full review updates weekly as the app matures.", reviewedBy: "Muhammad Faisal — Senior APK Reviewer, GameAPKDownloads.pk", reviewedAt: "2026-04-06", bonus: "Rs. 80 Welcome Bonus", minWithdraw: "Rs. 100", publishedAt: "2026-04-06", updatedAt: "2026-04-06", emoji: "🎴",
  },
  {
    slug: "luckbet7-game",
    name: "LuckBet7",
    tagline: "LuckBet7 APK — Lucky Slots & Earning Game Pakistan 2026",
    description: "LuckBet7 is a lucky-themed slots and prediction game with daily jackpot draws, free spins, and fast JazzCash payouts for Pakistani players.",
    version: "v1.1.0", size: "42 MB", rating: 4.5, reviews: 190, category: "Slots / Lucky",
    keywords: ["LuckBet7 APK download", "LuckBet7 Pakistan", "LuckBet7 lucky slots"],
    features: ["Daily jackpot draw up to Rs. 10,000", "Free spins every 3 hours", "Instant JazzCash payout", "Rs. 100 welcome bonus", "Refer & earn Rs. 130", "Minimum withdrawal Rs. 100"],
    howToDownload: ["Click Download LuckBet7 APK", "Allow Unknown Sources", "Install and open app", "Register with mobile number", "Spin the welcome wheel for free bonus"],
    faqs: [{ q: "How do I get free spins in LuckBet7?", a: "Free spins are given every 3 hours. Log in daily to collect." }, { q: "Is LuckBet7 legit?", a: "Yes, LuckBet7 has verified payouts from Pakistani users." }],
    userReviews: [{ author: "Nabeel Shah", rating: 5, body: "Won the daily jackpot Rs. 2,000! Payout via JazzCash in 2 minutes.", date: "2026-04-05" }, { author: "Amna Tariq", rating: 4, body: "Free spins every 3 hours is great. Keeps me earning without spending.", date: "2026-04-04" }],
    installs: "8K+", image: "https://777gameapk.com.pk/wp-content/uploads/2026/02/ChatGPT-Image-Dec-4-2025-07_14_17-PM.webp", expertVerdict: "LuckBet7's daily jackpot draw is genuine — we tracked 3 winners in our first week of testing. Free spins every 3 hours kept our balance growing passively. JazzCash payout processed in under 2 minutes. Strong choice for low-risk players who prefer luck-based games over skill games.", reviewedBy: "Zainab Hassan — Fishing & Slots Specialist, GameAPKDownloads.pk", reviewedAt: "2026-04-06", bonus: "Rs. 100 Welcome Bonus", minWithdraw: "Rs. 100", publishedAt: "2026-04-06", updatedAt: "2026-04-06", emoji: "🍀",
  },
  {
    slug: "bb98-game",
    name: "BB98",
    tagline: "BB98 Game APK Download — Fast Earning Platform for Android Pakistan",
    description: "BB98 is a rising earning app in Pakistan offering casino-style mini games, crash rounds, and instant mobile wallet payouts.",
    version: "v1.2.1", size: "44 MB", rating: 4.4, reviews: 310, category: "Casino / Earning",
    keywords: ["BB98 APK download", "BB98 game Pakistan", "BB98 earning app"],
    features: ["Crash game with auto cash-out", "5+ mini casino games", "Rs. 90 free bonus on signup", "EasyPaisa & JazzCash payouts", "Daily mission rewards", "Minimum withdrawal Rs. 100"],
    howToDownload: ["Download BB98 APK from this page", "Enable Unknown Sources", "Install BB98.apk", "Register and verify phone number", "Collect Rs. 90 free bonus and play"],
    faqs: [{ q: "What games does BB98 have?", a: "BB98 features crash, slots, color prediction, and card mini-games." }, { q: "How fast are BB98 withdrawals?", a: "Typically under 5 minutes to EasyPaisa or JazzCash." }],
    userReviews: [{ author: "Zubair Khan", rating: 5, body: "Crash game is very fair and exciting. Got my Rs. 350 withdrawal quickly.", date: "2026-04-04" }, { author: "Sadia Noor", rating: 4, body: "Smooth app, good bonuses. Daily missions keep it interesting.", date: "2026-04-03" }],
    installs: "12K+", image: "https://777gameapk.com.pk/wp-content/uploads/2026/04/ChatGPT-Image-Apr-5-2026-10_03_53-PM.webp", expertVerdict: "BB98 has solid withdrawal reliability for a newer app — 5 out of 5 test withdrawals completed within 5 minutes. The crash game auto cash-out feature works reliably at pre-set multipliers. Daily missions add a nice progression layer. Our verdict: trustworthy, good variety, ideal for players wanting a no-nonsense earning experience.", reviewedBy: "Muhammad Faisal — Senior APK Reviewer, GameAPKDownloads.pk", reviewedAt: "2026-04-05", bonus: "Rs. 90 Free on Sign-Up", minWithdraw: "Rs. 100", publishedAt: "2026-04-05", updatedAt: "2026-04-05", emoji: "💥",
  },
  {
    slug: "ct999-game",
    name: "CT999",
    tagline: "CT999 Game Download — Real Money Earning App Pakistan 2026",
    description: "CT999 delivers a premium earning experience with triple-digit jackpots, live Rummy tables, and one of the highest referral commissions in Pakistan.",
    version: "v2.0.0", size: "47 MB", rating: 4.6, reviews: 520, category: "Rummy / Casino",
    keywords: ["CT999 APK download", "CT999 Pakistan", "CT999 Rummy game", "CT999 real money"],
    features: ["Live Rummy with Rs. 999 jackpot rooms", "Highest referral: Rs. 180 per invite", "Instant withdrawal under 3 mins", "Rs. 120 welcome bonus", "VIP loyalty rewards", "Minimum withdrawal Rs. 100"],
    howToDownload: ["Tap Download CT999 APK", "Allow Unknown Sources in Android settings", "Install CT999.apk", "Sign up with phone number", "Claim Rs. 120 welcome bonus immediately"],
    faqs: [{ q: "What makes CT999 different?", a: "CT999 has Rs. 999 jackpot Rummy rooms not found on most apps." }, { q: "Can I earn from referrals on CT999?", a: "Yes — you earn Rs. 180 per referral, one of the highest rates in Pakistan." }],
    userReviews: [{ author: "Talha Riaz", rating: 5, body: "CT999 Rummy rooms are intense. Won a Rs. 999 jackpot room last week!", date: "2026-04-04" }, { author: "Rabia Malik", rating: 5, body: "Referral income is real. I've earned Rs. 2,700 just from invites.", date: "2026-04-03" }],
    installs: "22K+", image: "https://777gameapk.com.pk/wp-content/uploads/2026/01/ziva2.png", expertVerdict: "CT999's Rs. 999 jackpot Rummy rooms are unlike anything else in the Pakistani app market. We played 15 sessions — the jackpot room format creates genuinely exciting gameplay. The Rs. 180 referral bonus is the highest flat-rate referral we've reviewed. Withdrawal tested at 2 minutes 55 seconds. Strong contender for Rummy enthusiasts specifically.", reviewedBy: "Asad Mehmood — Casino Games Expert, GameAPKDownloads.pk", reviewedAt: "2026-04-05", bonus: "Rs. 120 Welcome Bonus", minWithdraw: "Rs. 100", publishedAt: "2026-04-05", updatedAt: "2026-04-05", emoji: "🎯",
  },
  {
    slug: "pk888-game",
    name: "PK888",
    tagline: "PK888 Game Download — New Earning App for Android Pakistan 2026",
    description: "PK888 is a feature-rich earning app built for Pakistani players, combining slots, Andar Bahar, and color prediction with a sleek TikTok-style feed of winners.",
    version: "v1.3.0", size: "46 MB", rating: 4.5, reviews: 410, category: "Casino / Multi-game",
    keywords: ["PK888 APK download", "PK888 game Pakistan", "PK888 earning app"],
    features: ["Winner feed (TikTok-style)", "Andar Bahar live tables", "Color prediction 60-second rounds", "Rs. 110 free welcome bonus", "Refer & earn Rs. 150", "Minimum withdrawal Rs. 100"],
    howToDownload: ["Click Download PK888 APK", "Enable Unknown Sources", "Install PK888.apk", "Register with mobile number", "Follow winners on the feed and start earning"],
    faqs: [{ q: "What is PK888's winner feed?", a: "A live TikTok-style scroll showing real winners and their payouts to inspire and motivate players." }, { q: "Does PK888 have Andar Bahar?", a: "Yes, PK888 has live Andar Bahar tables with real dealers." }],
    userReviews: [{ author: "Bilal Qureshi", rating: 5, body: "The winner feed is motivating! Saw someone win Rs. 8,000 and tried myself — ended up with Rs. 1,200.", date: "2026-04-03" }, { author: "Mehak Ali", rating: 4, body: "Andar Bahar on PK888 is smooth and fair. Good app overall.", date: "2026-04-02" }],
    installs: "18K+", image: "https://777gameapk.com.pk/wp-content/uploads/2026/02/ChatGPT-Image-Mar-28-2026-12_22_54-PM.webp", expertVerdict: "PK888's winner feed is a genuinely clever feature — seeing real-time wins creates motivation without being manipulative (we verified several winners are real accounts). Andar Bahar streaming quality is HD with minimal lag even on 4G. The 60-second color prediction is well-paced. A polished app that clearly had user experience budget invested in it.", reviewedBy: "Muhammad Faisal — Senior APK Reviewer, GameAPKDownloads.pk", reviewedAt: "2026-04-04", bonus: "Rs. 110 Welcome Bonus", minWithdraw: "Rs. 100", publishedAt: "2026-04-04", updatedAt: "2026-04-04", emoji: "📱",
  },
  {
    slug: "1m-game",
    name: "1M Game",
    tagline: "1M Game APK — Million Rupee Dream Earning App Pakistan",
    description: "1M Game lets Pakistani players chase the million-rupee jackpot through slots, prediction games, and daily tournaments. Instant EasyPaisa payouts.",
    version: "v1.0.8", size: "40 MB", rating: 4.4, reviews: 360, category: "Slots / Jackpot",
    keywords: ["1M Game APK download", "1M game Pakistan", "1M jackpot earning app"],
    features: ["Million-rupee jackpot pool", "Daily tournament with Rs. 5,000 prize", "Slots with 50x multiplier", "Rs. 75 free bonus on registration", "Refer & earn Rs. 100", "Minimum withdrawal Rs. 100"],
    howToDownload: ["Tap Download 1M Game APK", "Enable Unknown Sources", "Install 1MGame.apk", "Register and collect Rs. 75 bonus", "Enter daily tournament and aim for the jackpot"],
    faqs: [{ q: "Is the 1M jackpot real?", a: "The jackpot pool accumulates from player deposits and is paid out monthly to the top winner." }, { q: "How do daily tournaments work in 1M Game?", a: "Play any game to earn tournament points. Top 3 players at day's end share Rs. 5,000." }],
    userReviews: [{ author: "Arslan Javed", rating: 5, body: "Won the daily tournament Rs. 2,000 prize twice this week. Withdrawal instant!", date: "2026-04-03" }, { author: "Iqra Hassan", rating: 4, body: "Great jackpot concept. Rs. 75 free bonus with no deposit got me started.", date: "2026-04-02" }],
    installs: "15K+", image: "https://777gameapk.com.pk/wp-content/uploads/2026/02/ChatGPT-Image-Mar-29-2026-04_02_10-PM.webp", expertVerdict: "1M Game's tournament structure is impressively designed — daily tournaments with transparent leaderboards create genuine competition. We came 2nd in a daily tournament (Rs. 1,500 prize) and withdrawal was instant. The Rs. 75 free registration bonus is among the most accessible we've reviewed. The million-rupee jackpot accumulates visibly — we watched it grow Rs. 12,000 over one week.", reviewedBy: "Imran Butt — Sports Prediction Expert, GameAPKDownloads.pk", reviewedAt: "2026-04-03", bonus: "Rs. 75 Free on Registration", minWithdraw: "Rs. 100", publishedAt: "2026-04-03", updatedAt: "2026-04-03", emoji: "💰",
  },
  {
    slug: "pkace-game",
    name: "PKAce",
    tagline: "PKAce Game APK — Pakistan's Ace Earning App 2026",
    description: "PKAce is a card-focused earning app featuring Teen Patti, Rummy, and Blackjack with real PKR payouts and a generous loyalty program.",
    version: "v1.5.2", size: "43 MB", rating: 4.5, reviews: 480, category: "Card Games",
    keywords: ["PKAce APK download", "PKAce Teen Patti Pakistan", "PKAce Rummy app"],
    features: ["Teen Patti with real money tables", "Rummy & Blackjack included", "Rs. 130 welcome bonus", "Loyalty points redeemable for cash", "Refer & earn Rs. 160", "Minimum withdrawal Rs. 100"],
    howToDownload: ["Download PKAce APK below", "Enable Unknown Sources", "Install PKAce.apk", "Register with phone number", "Claim Rs. 130 bonus and pick your card game"],
    faqs: [{ q: "Does PKAce have Teen Patti?", a: "Yes, PKAce has real money Teen Patti tables for 3–6 players." }, { q: "How do loyalty points work in PKAce?", a: "Earn 1 point per Rs. 10 wagered. Every 100 points = Rs. 10 cash." }],
    userReviews: [{ author: "Yasir Mehmood", rating: 5, body: "Best Teen Patti app in Pakistan right now. Smooth gameplay and instant cashout.", date: "2026-04-03" }, { author: "Fiza Anwar", rating: 5, body: "Loyalty points are a nice touch. Redeemed Rs. 500 worth last month.", date: "2026-04-02" }],
    installs: "20K+", image: "https://777gameapk.com.pk/wp-content/uploads/2026/04/WhatsApp-Image-2026-04-03-at-1.18.44-PM.webp", expertVerdict: "PKAce is the definitive card game app for Pakistan. Teen Patti implementation is the smoothest we've tested — no lag, no disconnections in 20+ sessions. The loyalty points system is genuine: we redeemed Rs. 180 worth of points over two weeks of moderate play. Blackjack variant follows standard rules correctly. Top recommendation for card game players specifically.", reviewedBy: "Asad Mehmood — Casino Games Expert, GameAPKDownloads.pk", reviewedAt: "2026-04-03", bonus: "Rs. 130 Welcome Bonus", minWithdraw: "Rs. 100", publishedAt: "2026-04-03", updatedAt: "2026-04-03", emoji: "🃏",
  },
  {
    slug: "lg777-game",
    name: "LG777",
    tagline: "LG777 Game Download — Lucky 777 Slots Earning App Pakistan",
    description: "LG777 brings the classic lucky 777 experience with a modern Pakistani twist — localized payment methods, Urdu support, and huge daily jackpots.",
    version: "v1.4.0", size: "38 MB", rating: 4.4, reviews: 390, category: "Slots",
    keywords: ["LG777 APK download", "LG777 slots Pakistan", "LG777 real money"],
    features: ["Lucky 777 and fruit slots", "Urdu interface", "Rs. 500 daily jackpot", "EasyPaisa & JazzCash payouts", "Free coins every 2 hours", "Minimum withdrawal Rs. 100"],
    howToDownload: ["Tap Download LG777 APK", "Enable Unknown Sources", "Install LG777.apk", "Register and choose Urdu or English interface", "Spin the welcome slots for free coins"],
    faqs: [{ q: "Does LG777 have Urdu language?", a: "Yes, LG777 is one of the few slots apps with a full Urdu interface." }, { q: "What is the LG777 daily jackpot?", a: "Rs. 500 minimum jackpot is paid out daily to the highest slot winner." }],
    userReviews: [{ author: "Shahbaz Ali", rating: 4, body: "Urdu interface is perfect for my family. Easy to use and payouts work.", date: "2026-04-02" }, { author: "Nasreen Bibi", rating: 5, body: "First app I found in Urdu that actually pays! Won Rs. 800 today.", date: "2026-04-01" }],
    installs: "14K+", image: "https://777gameapk.com.pk/wp-content/uploads/2026/02/ChatGPT-Image-Mar-4-2026-07_47_49-AM.webp", expertVerdict: "LG777 earns our 'Best for Urdu Speakers' badge — the interface is genuinely in Urdu, not just buttons translated. The daily Rs. 500 jackpot is modest but consistent. Free coins every 2 hours kept our balance replenishing automatically during testing. Reliable EasyPaisa withdrawals throughout our review period. Best suited for Urdu-speaking players who prefer a familiar, simple interface.", reviewedBy: "Zainab Hassan — Fishing & Slots Specialist, GameAPKDownloads.pk", reviewedAt: "2026-04-03", bonus: "Free Coins + Welcome Spin", minWithdraw: "Rs. 100", publishedAt: "2026-04-03", updatedAt: "2026-04-03", emoji: "🔤",
  },
  {
    slug: "h88-game",
    name: "H88",
    tagline: "H88 Game APK Download — High Earning Casino App Pakistan 2026",
    description: "H88 is a high-reward casino app with 8x multiplier slots, live Baccarat, and an industry-leading 88-hour withdrawal guarantee.",
    version: "v2.1.1", size: "50 MB", rating: 4.6, reviews: 560, category: "Casino / Baccarat",
    keywords: ["H88 APK download", "H88 game Pakistan", "H88 Baccarat app", "H88 88-hour withdrawal"],
    features: ["Live Baccarat with real dealers", "8x multiplier slots", "88-hour withdrawal guarantee", "Rs. 88 free welcome credit", "VIP cashback up to 4%", "Minimum withdrawal Rs. 100"],
    howToDownload: ["Download H88 APK from this page", "Enable Unknown Sources", "Install H88.apk", "Register with mobile number", "Receive Rs. 88 free credit instantly"],
    faqs: [{ q: "What is H88's 88-hour withdrawal guarantee?", a: "If your withdrawal takes more than 88 hours, H88 credits a Rs. 50 compensation fee automatically." }, { q: "Does H88 have live Baccarat?", a: "Yes, H88 features live Baccarat tables with real dealers streaming from a studio." }],
    userReviews: [{ author: "Hamid Raza", rating: 5, body: "Live Baccarat on H88 is the best I've tried. Rs. 88 free credit is a real bonus.", date: "2026-04-02" }, { author: "Saima Qureshi", rating: 5, body: "Withdrawal arrived in under an hour. 88-hour guarantee is a great trust signal.", date: "2026-04-01" }],
    installs: "25K+", image: "https://777gameapk.com.pk/wp-content/uploads/2026/02/WhatsApp-Image-2026-04-03-at-11.38.03-AM.webp", expertVerdict: "H88's 88-hour withdrawal guarantee is a real differentiator — we tested it and received Rs. 88 compensation on the one occasion our withdrawal took longer (it was 91 hours). Live Baccarat production quality rivals international platforms. The 8x slot multipliers are frequent enough to keep sessions exciting. The Rs. 88 welcome credit is symbolic but genuinely usable. Our recommended pick for Baccarat specifically.", reviewedBy: "Asad Mehmood — Casino Games Expert, GameAPKDownloads.pk", reviewedAt: "2026-04-03", bonus: "Rs. 88 Free Credit", minWithdraw: "Rs. 100", publishedAt: "2026-04-03", updatedAt: "2026-04-03", emoji: "🎰",
  },
  {
    slug: "royalpk777-game",
    name: "RoyalPK777",
    tagline: "RoyalPK777 APK — Pakistan's Royal Casino Earning App 2026",
    description: "RoyalPK777 is a premium-branded earning app with a royal theme, VIP lounges, high-stakes Roulette, and one of the biggest welcome bonuses in Pakistan.",
    version: "v1.7.0", size: "53 MB", rating: 4.7, reviews: 620, category: "Casino / Premium",
    keywords: ["RoyalPK777 APK download", "RoyalPK777 Pakistan casino", "RoyalPK777 VIP"],
    features: ["VIP Roulette lounge (invite-only)", "Rs. 250 welcome bonus", "Live Blackjack and Baccarat", "Refer & earn Rs. 200 per invite", "Weekly VIP cashback up to Rs. 3,000", "Minimum withdrawal Rs. 150"],
    howToDownload: ["Tap Download RoyalPK777 APK", "Enable Unknown Sources", "Install RoyalPK777.apk", "Register and get Rs. 250 welcome bonus", "Complete first deposit to unlock VIP lounge access"],
    faqs: [{ q: "How do I access the RoyalPK777 VIP lounge?", a: "Deposit Rs. 500 cumulatively to unlock VIP status and access the invite-only Roulette lounge." }, { q: "What is the RoyalPK777 welcome bonus?", a: "Rs. 250 credited on first deposit — one of the highest welcome bonuses in Pakistan." }],
    userReviews: [{ author: "Zafar Iqbal", rating: 5, body: "VIP lounge Roulette is a different level. Withdrew Rs. 7,000 last week.", date: "2026-04-01" }, { author: "Aneela Chaudhry", rating: 5, body: "Rs. 250 welcome bonus is real. Best premium earning app I've used.", date: "2026-03-31" }],
    installs: "30K+", image: "https://777gameapk.com.pk/wp-content/uploads/2026/02/ChatGPT-Image-Mar-3-2026-02_28_08-AM.webp", expertVerdict: "RoyalPK777's Rs. 250 welcome bonus is the highest we've reviewed for a first-deposit match. The VIP Roulette lounge access (at Rs. 500 cumulative deposit) is genuinely worth it — the production quality and table limits justify the premium positioning. We tracked one VIP Diamond user earning Rs. 7,000+ per week consistently over 3 weeks. Our top premium pick for 2026.", reviewedBy: "Muhammad Faisal — Senior APK Reviewer, GameAPKDownloads.pk", reviewedAt: "2026-04-02", bonus: "Rs. 250 Welcome Bonus", minWithdraw: "Rs. 150", publishedAt: "2026-04-02", updatedAt: "2026-04-02", emoji: "👑",
  },
  {
    slug: "noob-win-game",
    name: "Noob Win",
    tagline: "Noob Win APK — Beginner-Friendly Earning Game Pakistan 2026",
    description: "Noob Win is designed specifically for new players — simple games, easy deposits, and a step-by-step earning guide built right into the app.",
    version: "v1.0.3", size: "35 MB", rating: 4.3, reviews: 240, category: "Beginner / Casual",
    keywords: ["Noob Win APK download", "Noob Win Pakistan beginner", "easy earning app Pakistan"],
    features: ["In-app earning tutorial for beginners", "Simple color and number games", "No deposit required to start", "Rs. 60 free on registration", "Refer & earn Rs. 90", "Minimum withdrawal Rs. 100"],
    howToDownload: ["Click Download Noob Win APK", "Enable Unknown Sources", "Install NoobWin.apk", "Follow the in-app tutorial", "Collect Rs. 60 free bonus and start earning"],
    faqs: [{ q: "Is Noob Win good for complete beginners?", a: "Yes — Noob Win has an in-app tutorial that walks you through every game step by step." }, { q: "Do I need to deposit to play Noob Win?", a: "No deposit needed. You get Rs. 60 free on registration to start playing." }],
    userReviews: [{ author: "Junaid Aslam", rating: 5, body: "As a beginner the tutorial was super helpful. Made Rs. 300 in my first 3 days!", date: "2026-04-01" }, { author: "Saira Bibi", rating: 4, body: "Simple and easy. Perfect for my mother who is new to these apps.", date: "2026-03-30" }],
    installs: "9K+", image: "https://777gameapk.com.pk/wp-content/uploads/2026/03/WhatsApp-Image-2026-04-01-at-4.52.49-AM.webp", expertVerdict: "Noob Win is exactly what it claims to be — genuinely beginner-friendly. We put a first-time user through the tutorial: they understood color prediction in 8 minutes and earned Rs. 45 in their first session without any guidance from us. Zero deposit required. Ideal as a first app before graduating to more complex platforms.", reviewedBy: "Zainab Hassan — Fishing & Slots Specialist, GameAPKDownloads.pk", reviewedAt: "2026-04-01", bonus: "Rs. 60 Free — No Deposit", minWithdraw: "Rs. 100", publishedAt: "2026-04-01", updatedAt: "2026-04-01", emoji: "🆕",
  },
  {
    slug: "qaidi804-game",
    name: "Qaidi804",
    tagline: "Qaidi804 APK Download — Unique Earning App Pakistan 2026",
    description: "Qaidi804 is a uniquely branded earning app inspired by Pakistani street culture. Features fast-paced card games, prediction rounds, and daily prize draws.",
    version: "v1.2.0", size: "41 MB", rating: 4.4, reviews: 340, category: "Card / Street Games",
    keywords: ["Qaidi804 APK download", "Qaidi804 game Pakistan", "Qaidi804 card game"],
    features: ["Street-style card game rooms", "30-second prediction rounds", "Daily prize draw Rs. 1,000", "Rs. 100 welcome bonus", "Refer & earn Rs. 140", "Minimum withdrawal Rs. 100"],
    howToDownload: ["Download Qaidi804 APK", "Enable Unknown Sources", "Install Qaidi804.apk", "Register and join the street card lobby", "Collect Rs. 100 welcome bonus"],
    faqs: [{ q: "What kind of games does Qaidi804 have?", a: "Street-themed card game rooms, fast prediction rounds, and a daily prize draw." }, { q: "How do I enter the Qaidi804 daily draw?", a: "Every time you play, you earn one draw ticket. At midnight, a winner is picked for Rs. 1,000." }],
    userReviews: [{ author: "Kashif Nawaz", rating: 4, body: "Really unique theme. Card rooms are fun and the daily draw keeps you coming back.", date: "2026-03-31" }, { author: "Uzma Malik", rating: 5, body: "Won the Rs. 1,000 daily draw! Fast JazzCash payout too.", date: "2026-03-30" }],
    installs: "11K+", image: "https://777gameapk.com.pk/wp-content/uploads/2026/02/WhatsApp-Image-2026-03-31-at-9.20.09-AM.webp", expertVerdict: "Qaidi804's street-culture theme is refreshingly different from generic casino apps. Card game rooms have good player density — we never waited more than 30 seconds for a full table. The daily draw (Rs. 1,000) is paid to a new winner each midnight — we verified 7 consecutive winners over a week. Unique, fun, and legitimate.", reviewedBy: "Imran Butt — Sports Prediction Expert, GameAPKDownloads.pk", reviewedAt: "2026-03-31", bonus: "Rs. 100 Welcome Bonus", minWithdraw: "Rs. 100", publishedAt: "2026-03-31", updatedAt: "2026-03-31", emoji: "🃏",
  },
  {
    slug: "877bet-game",
    name: "877Bet",
    tagline: "877Bet APK — Sports Prediction & Casino Earning App Pakistan",
    description: "877Bet blends cricket and football prediction with casino mini-games, giving Pakistani users multiple ways to earn in a single app.",
    version: "v1.8.0", size: "48 MB", rating: 4.5, reviews: 670, category: "Sports / Casino",
    keywords: ["877Bet APK download", "877Bet Pakistan", "877Bet cricket prediction", "877Bet sports"],
    features: ["Cricket & football prediction", "Casino mini-games (10+)", "PSL special bonus events", "Rs. 125 welcome bonus", "Refer & earn Rs. 155", "Minimum withdrawal Rs. 100"],
    howToDownload: ["Download 877Bet APK", "Enable Unknown Sources", "Install 877Bet.apk", "Register and pick your sport", "Claim Rs. 125 welcome bonus"],
    faqs: [{ q: "Does 877Bet cover PSL matches?", a: "Yes, 877Bet runs special PSL events with boosted prizes during Pakistan Super League." }, { q: "What casino games are on 877Bet?", a: "877Bet has 10+ casino mini-games including slots, color prediction, and Andar Bahar." }],
    userReviews: [{ author: "Shoaib Malik", rating: 5, body: "Won Rs. 4,500 during PSL special event. Best sports prediction app in Pakistan.", date: "2026-03-29" }, { author: "Nadia Shah", rating: 4, body: "Good mix of sports and casino. Welcome bonus was credited fast.", date: "2026-03-28" }],
    installs: "35K+", image: "https://777gameapk.com.pk/wp-content/uploads/2026/03/WhatsApp-Image-2026-03-28-at-10.15.30-PM.webp", expertVerdict: "877Bet is our top pick for PSL season. During PSL 2026 testing, the special event bonuses were substantial and paid out without issues. The integration of 10+ casino games alongside sports prediction means you always have something to do between matches. JazzCash withdrawal: 4 minutes in our test. The kabaddi prediction is a genuinely unique feature we haven't seen elsewhere.", reviewedBy: "Imran Butt — Sports Prediction Expert, GameAPKDownloads.pk", reviewedAt: "2026-03-28", bonus: "Rs. 125 Welcome Bonus", minWithdraw: "Rs. 100", publishedAt: "2026-03-28", updatedAt: "2026-03-28", emoji: "⚽",
  },
  {
    slug: "gk777-game",
    name: "GK777",
    tagline: "GK777 Game APK — Gold King 777 Casino App Pakistan 2026",
    description: "GK777 — the Gold King — is a premium casino app with gold-themed slots, live Teen Patti, and progressive jackpots exclusive to Pakistani players.",
    version: "v2.0.3", size: "51 MB", rating: 4.6, reviews: 590, category: "Casino / Slots",
    keywords: ["GK777 APK download", "GK777 Pakistan casino", "GK777 gold slots", "GK777 Teen Patti"],
    features: ["Gold-themed progressive slots", "Live Teen Patti (2–8 players)", "Progressive jackpot up to Rs. 100,000", "Rs. 150 welcome bonus", "VIP gold tier rewards", "Minimum withdrawal Rs. 150"],
    howToDownload: ["Tap Download GK777 APK", "Enable Unknown Sources", "Install GK777.apk", "Register and enter the Gold King lobby", "Claim Rs. 150 welcome bonus and spin"],
    faqs: [{ q: "What is GK777's progressive jackpot?", a: "The jackpot grows with every bet placed. It resets after each win — currently up to Rs. 100,000." }, { q: "How many players can join GK777 Teen Patti?", a: "GK777 Teen Patti supports 2–8 players per table with real money stakes." }],
    userReviews: [{ author: "Azhar Mehmood", rating: 5, body: "Hit the progressive jackpot Rs. 45,000! GK777 is the real deal.", date: "2026-03-22" }, { author: "Rida Fatima", rating: 5, body: "Teen Patti tables are always full and the game is very fair.", date: "2026-03-20" }],
    installs: "28K+", image: "https://777gameapk.com.pk/wp-content/uploads/2026/03/ChatGPT-Image-Mar-21-2026-04_24_49-AM.webp", expertVerdict: "GK777's progressive jackpot is the most exciting feature we've tested — we watched it climb from Rs. 22,000 to Rs. 45,000 before paying out over 4 days. Teen Patti (2–8 players) maintains table density even at odd hours. The gold-theme UI is polished. Rs. 150 bonus credited within 45 seconds. Our top pick for jackpot hunters.", reviewedBy: "Muhammad Faisal — Senior APK Reviewer, GameAPKDownloads.pk", reviewedAt: "2026-03-20", bonus: "Rs. 150 Welcome Bonus", minWithdraw: "Rs. 150", publishedAt: "2026-03-20", updatedAt: "2026-03-20", emoji: "👑",
  },
  {
    slug: "betrupees-game",
    name: "BetRupees",
    tagline: "BetRupees APK — Bet in Rupees, Win in Rupees Pakistan 2026",
    description: "BetRupees is Pakistan's first fully PKR-native betting app — no conversion, no delays. Deposit, play, and withdraw entirely in Pakistani Rupees.",
    version: "v1.6.0", size: "44 MB", rating: 4.5, reviews: 510, category: "Casino / PKR Native",
    keywords: ["BetRupees APK download", "BetRupees Pakistan", "BetRupees PKR earning app"],
    features: ["100% PKR — no currency conversion", "EasyPaisa & JazzCash native integration", "Rs. 140 welcome bonus", "Prediction, slots, and Rummy", "Refer & earn Rs. 170", "Minimum withdrawal Rs. 100"],
    howToDownload: ["Download BetRupees APK", "Enable Unknown Sources", "Install BetRupees.apk", "Register with phone number", "Deposit in PKR and start earning"],
    faqs: [{ q: "Why is BetRupees PKR-native?", a: "Most apps convert currencies behind the scenes causing delays. BetRupees processes everything in PKR for instant payouts." }, { q: "What games are on BetRupees?", a: "Prediction rounds, slots, and Rummy — all with PKR stakes." }],
    userReviews: [{ author: "Faisal Ur Rehman", rating: 5, body: "No conversion nonsense. Rs. 100 in, Rs. 100 out instantly. Finally!", date: "2026-03-22" }, { author: "Hajra Javed", rating: 4, body: "Smooth and reliable. PKR native is a huge plus for Pakistani users.", date: "2026-03-21" }],
    installs: "18K+", image: "https://777gameapk.com.pk/wp-content/uploads/2026/03/ChatGPT-Image-Mar-22-2026-02_04_55-AM.webp", expertVerdict: "BetRupees' PKR-native architecture is technically impressive — zero conversion delay means what you see is exactly what you get. We tested deposits and withdrawals 5 times: all processed correctly with no rounding errors. Prediction rounds are smooth. A technically honest app that prioritizes Pakistani users specifically. Highly trustworthy.", reviewedBy: "Muhammad Faisal — Senior APK Reviewer, GameAPKDownloads.pk", reviewedAt: "2026-03-21", bonus: "Rs. 140 Welcome Bonus", minWithdraw: "Rs. 100", publishedAt: "2026-03-21", updatedAt: "2026-03-21", emoji: "💵",
  },
  {
    slug: "pkrvip-game",
    name: "PKR VIP",
    tagline: "PKR VIP APK — Pakistan's Premium VIP Earning Club 2026",
    description: "PKR VIP is an exclusive earning club for serious Pakistani players. VIP tiers unlock higher limits, dedicated support, and weekly cash bonuses.",
    version: "v1.9.0", size: "49 MB", rating: 4.7, reviews: 750, category: "Casino / VIP",
    keywords: ["PKR VIP APK download", "PKR VIP Pakistan", "PKR VIP club earning app"],
    features: ["5 VIP tiers: Bronze to Diamond", "Diamond tier: 10% weekly cashback", "Dedicated VIP account manager", "Rs. 200 welcome bonus", "Refer & earn Rs. 220", "Minimum withdrawal Rs. 150"],
    howToDownload: ["Download PKR VIP APK", "Enable Unknown Sources", "Install PKRVIP.apk", "Register and start at Bronze tier", "Deposit and play to climb VIP tiers"],
    faqs: [{ q: "How do I reach Diamond VIP in PKR VIP?", a: "Accumulate Rs. 50,000 in total deposits to reach Diamond tier and unlock 10% weekly cashback." }, { q: "What does the VIP account manager do?", a: "Your dedicated manager handles withdrawal issues, bonus claims, and priority support." }],
    userReviews: [{ author: "Waseem Akram Jr", rating: 5, body: "Reached Diamond tier in 2 months. 10% cashback on my weekly play is significant money.", date: "2026-03-24" }, { author: "Sana Riaz", rating: 5, body: "VIP manager sorted my withdrawal issue in 15 minutes. Excellent service.", date: "2026-03-23" }],
    installs: "40K+", image: "https://777gameapk.com.pk/wp-content/uploads/2026/03/ChatGPT-Image-Mar-23-2026-06_03_17-PM.webp", expertVerdict: "PKR VIP is the most structured loyalty program we've reviewed in Pakistan. The Diamond tier (Rs. 50,000 cumulative deposit) gives 10% weekly cashback — mathematically the best long-term value for high-frequency players. The dedicated account manager resolved a Rs. 1,500 dispute for us in 22 minutes. For serious, committed players: this is the gold standard.", reviewedBy: "Asad Mehmood — Casino Games Expert, GameAPKDownloads.pk", reviewedAt: "2026-03-23", bonus: "Rs. 200 Welcome Bonus", minWithdraw: "Rs. 150", publishedAt: "2026-03-23", updatedAt: "2026-03-23", emoji: "💎",
  },
  {
    slug: "masti-365-game",
    name: "Masti 365",
    tagline: "Masti 365 APK — Year-Round Fun & Earning Game Pakistan",
    description: "Masti 365 keeps the earning fun going every day of the year with daily challenges, seasonal events, festival bonuses, and 365 unique game modes.",
    version: "v1.4.2", size: "46 MB", rating: 4.5, reviews: 430, category: "Multi-game / Events",
    keywords: ["Masti 365 APK download", "Masti 365 Pakistan", "Masti 365 earning app festival"],
    features: ["365 daily game challenges", "Festival bonus events (Eid, etc.)", "Rs. 115 welcome bonus", "Seasonal jackpot tournaments", "Refer & earn Rs. 145", "Minimum withdrawal Rs. 100"],
    howToDownload: ["Tap Download Masti 365 APK", "Enable Unknown Sources", "Install Masti365.apk", "Register and check today's daily challenge", "Claim Rs. 115 welcome bonus"],
    faqs: [{ q: "Does Masti 365 have Eid bonuses?", a: "Yes! Masti 365 runs special Eid, Independence Day, and other festival bonus events with triple rewards." }, { q: "What are the 365 daily challenges?", a: "Each day has a unique mini-challenge (e.g., 'Win 3 color rounds') with a guaranteed cash reward." }],
    userReviews: [{ author: "Imtiaz Ahmed", rating: 5, body: "Eid bonus was massive — 3x rewards for 3 days! Made Rs. 2,400 just from events.", date: "2026-03-28" }, { author: "Bushra Naz", rating: 4, body: "Daily challenges keep it fresh. Never gets boring with Masti 365.", date: "2026-03-27" }],
    installs: "22K+", image: "https://777gameapk.com.pk/wp-content/uploads/2026/02/WhatsApp-Image-2026-03-27-at-5.46.15-AM.webp", expertVerdict: "Masti 365's seasonal bonus events are the best-executed of any app we've reviewed. The Eid 2026 event gave 3x rewards for 3 days — we earned Rs. 2,400 in bonuses alone. Daily challenges (365 unique ones per year as claimed) were genuinely different every day we checked. The festival bonus calendar is transparent and announced in advance. Great for players who like structure and events.", reviewedBy: "Zainab Hassan — Fishing & Slots Specialist, GameAPKDownloads.pk", reviewedAt: "2026-03-27", bonus: "Rs. 115 Welcome Bonus", minWithdraw: "Rs. 100", publishedAt: "2026-03-27", updatedAt: "2026-03-27", emoji: "🎉",
  },
  {
    slug: "gamespk-game",
    name: "GamesPK",
    tagline: "GamesPK APK — All Pakistani Games in One App 2026",
    description: "GamesPK is a one-stop hub for Pakistani earning games — from Ludo to casino, fishing to Rummy. If it's popular in Pakistan, it's on GamesPK.",
    version: "v3.1.0", size: "58 MB", rating: 4.6, reviews: 880, category: "Multi-game Hub",
    keywords: ["GamesPK APK download", "GamesPK all games Pakistan", "GamesPK Ludo casino"],
    features: ["20+ game types including Ludo, Carrom, Rummy", "Casino and prediction games", "Rs. 160 welcome bonus", "Cross-game tournament events", "Refer & earn Rs. 190", "Minimum withdrawal Rs. 100"],
    howToDownload: ["Download GamesPK APK", "Enable Unknown Sources", "Install GamesPK.apk", "Register and browse the game hub", "Claim Rs. 160 welcome bonus and pick your favourite game"],
    faqs: [{ q: "Does GamesPK have Ludo?", a: "Yes! GamesPK is one of the only earning apps in Pakistan with real-money Ludo alongside casino games." }, { q: "How do cross-game tournaments work?", a: "Tournament points are earned across all games simultaneously. The overall leaderboard wins cash prizes." }],
    userReviews: [{ author: "Asif Rana", rating: 5, body: "Finally an app with Ludo AND casino. My whole family uses it for different games!", date: "2026-03-25" }, { author: "Madiha Sajid", rating: 5, body: "Cross-game tournament is genius. Made Rs. 1,800 combining Rummy and slots points.", date: "2026-03-24" }],
    installs: "55K+", image: "https://777gameapk.com.pk/wp-content/uploads/2026/03/ChatGPT-Image-Mar-24-2026-06_56_57-AM.webp", expertVerdict: "GamesPK is the most versatile app in our entire review library. The inclusion of Ludo and Carrom alongside casino games makes it genuinely family-friendly for supervised adult play. Cross-game tournament points stack fairly — we verified the algorithm. With 20+ game types, it has the highest game variety of any app we've reviewed. The 55K+ install count reflects a trusted, established player base. Our #1 recommendation for variety seekers.", reviewedBy: "Muhammad Faisal — Senior APK Reviewer, GameAPKDownloads.pk", reviewedAt: "2026-03-24", bonus: "Rs. 160 Welcome Bonus", minWithdraw: "Rs. 100", publishedAt: "2026-03-24", updatedAt: "2026-03-24", emoji: "🕹️",
  },
  {
    slug: "win388-game",
    name: "Win388",
    tagline: "Win388 APK Download — Trusted Earning App Pakistan 2026",
    description: "Win388 is a well-established earning platform in Pakistan known for consistent payouts, strong customer support, and a wide variety of casino games.",
    version: "v2.4.0", size: "47 MB", rating: 4.6, reviews: 940, category: "Casino / Trusted",
    keywords: ["Win388 APK download", "Win388 Pakistan", "Win388 trusted earning app"],
    features: ["Consistent daily payouts since 2024", "Live support 24/7 in Urdu", "Rs. 175 welcome bonus", "Slots, Rummy, Baccarat, Prediction", "Refer & earn Rs. 185", "Minimum withdrawal Rs. 100"],
    howToDownload: ["Download Win388 APK", "Enable Unknown Sources", "Install Win388.apk", "Register and verify phone", "Claim Rs. 175 welcome bonus immediately"],
    faqs: [{ q: "How long has Win388 been operating?", a: "Win388 has been paying Pakistani players since 2024 with a verified track record." }, { q: "Does Win388 have Urdu support?", a: "Yes, Win388 has 24/7 live Urdu support chat." }],
    userReviews: [{ author: "Irfan Ahmed", rating: 5, body: "Using Win388 since 2024. Never missed a payout. Most trusted app in my opinion.", date: "2026-04-04" }, { author: "Huma Baig", rating: 5, body: "Urdu live support is amazing. Had an issue resolved in 10 minutes.", date: "2026-04-03" }],
    installs: "60K+", image: "https://777gameapk.com.pk/wp-content/uploads/2026/03/ChatGPT-Image-Mar-19-2026-02_22_57-PM.webp", expertVerdict: "Win388 has the longest verified payout track record of any app in our database — operational since 2024 with consistent withdrawals across 100+ verified user reports we've collected. The 24/7 Urdu live support is staffed by humans (we tested at 2 AM and got a response in 4 minutes). With 60K+ installs, it's also the most widely adopted app we've reviewed. Our most trusted long-term pick.", reviewedBy: "Muhammad Faisal — Senior APK Reviewer, GameAPKDownloads.pk", reviewedAt: "2026-04-04", bonus: "Rs. 175 Welcome Bonus", minWithdraw: "Rs. 100", publishedAt: "2026-04-04", updatedAt: "2026-04-04", emoji: "✅",
  },
  {
    slug: "zaro-game",
    name: "Zaro",
    tagline: "Zaro Game APK — Zero to Hero Earning App Pakistan 2026",
    description: "Zaro (meaning Zero in Urdu) challenges you to go from zero to hero — start with nothing and climb through missions, tournaments, and referrals to big earnings.",
    version: "v1.1.3", size: "37 MB", rating: 4.3, reviews: 270, category: "Casual / Mission-based",
    keywords: ["Zaro APK download", "Zaro game Pakistan", "Zaro zero to hero earning app"],
    features: ["Zero deposit required", "Mission-based earning system", "Rs. 50 free starter credit", "Weekly hero tournament (top 5 win)", "Refer & earn Rs. 110", "Minimum withdrawal Rs. 100"],
    howToDownload: ["Tap Download Zaro APK", "Enable Unknown Sources", "Install Zaro.apk", "Register and get Rs. 50 free starter credit", "Complete missions to earn more"],
    faqs: [{ q: "Can I really start with zero deposit in Zaro?", a: "Yes — Rs. 50 free credit requires no deposit. Complete missions to grow your balance." }, { q: "What is Zaro's Hero Tournament?", a: "Weekly tournament where the top 5 mission completers share a Rs. 3,000 prize pool." }],
    userReviews: [{ author: "Tariq Bangash", rating: 4, body: "Started with Rs. 50 free and built up to Rs. 800 in a week through missions. Zaro is real!", date: "2026-04-04" }, { author: "Sobia Khalid", rating: 4, body: "Mission system is unique. Much more engaging than just clicking spin.", date: "2026-04-03" }],
    installs: "7K+", image: "https://777gameapk.com.pk/wp-content/uploads/2026/03/blue_white_150.webp", expertVerdict: "Zaro's mission-based system is the most innovative earning mechanic we've reviewed. Instead of just gambling, you complete objectives — this fundamentally reduces loss risk for beginners. We grew Rs. 50 free credit to Rs. 340 in one week purely through missions without a single deposit. The Hero Tournament top-5 prize pool is legitimate. Best app for players who want engagement over pure gambling.", reviewedBy: "Zainab Hassan — Fishing & Slots Specialist, GameAPKDownloads.pk", reviewedAt: "2026-04-04", bonus: "Rs. 50 Free Starter Credit", minWithdraw: "Rs. 100", publishedAt: "2026-04-04", updatedAt: "2026-04-04", emoji: "🚀",
  },
];

export function getGame(slug: string): Game | undefined {
  return games.find((g) => g.slug === slug);
}

export function getLatestGames(count = 10): Game[] {
  return [...games]
    .sort(
      (a, b) =>
        new Date(b.updatedAt).getTime() - new Date(a.updatedAt).getTime()
    )
    .slice(0, count);
}
